###

POST http://localhost:3000/register/
Content-Type: application/json/

{   
    "name":"Adam Richard",
    "username":"adam_richard",
    "password": "richa",
    "gender": "Male",
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"JoeBiden",
    "password": "biden@123"
}



###
GET http://localhost:3000/user/following/


###
GET http://localhost:3000/user/followers/

###
GET http://localhost:3000/tweets/3

###
GET http://localhost:3000/tweets/3/likes

###
GET http://localhost:3000/tweets/3/replies
### 
DELETE  http://localhost:3000/tweets/:2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgzODE0NzcyfQ.cjs4bsAHzx_ipU1A59TriCIPZaS6kg0yM1Y3yoURR_Q